### ISSUE TITLE
[REQ] Toggle command

### ISSUE THREAD

**Issue by ovidius72** [dstein64/vim-win#1]
Hi, thanks for this useful plugin. Is there any way to configure it so that it exits from the "vim-win mode" hitting a key that is not <Esc>. I mapped it to `,` and i want that when I press `,` again it exits from vim-win. How can I do that. 
I've tried mapping `,` to <Esc> in the settings, like so but it doesn't work.
```
let g:win_ext_command_map = {
     ..........
      \   ',': '<Esc>',
      \ }
```
Thanks.

**Comment by ovidius72** [comment]
I've just seen your comment on [reddit](https://www.reddit.com/r/vim/comments/eli713/vimwin_a_plugin_for_managing_windows/fdjae0p?utm_source=share&utm_medium=web2x). The new added command  works just fine.

**Comment by llinfeng** [comment]
`'Win#exit'` is the what it takes to quit `vim-win` properly. Here is my current setting to use `q` and `<cr>` to get back to normal mode.
```
let g:win_ext_command_map = {'q': 'Win#exit',"\<cr>": 'Win#exit'}
```
Source: [this pointer](https://github.com/dstein64/vim-win/issues/1#issuecomment-572065984) to a [reddit post](https://www.reddit.com/r/vim/comments/eli713/vimwin_a_plugin_for_managing_windows/fdjae0p/?utm_source=share&utm_medium=web2x)
