### ISSUE TITLE
error in neovim when execute c or q

### ISSUE THREAD

**Issue by ghrejoe** [dstein64/vim-win#2]
function win#win[21]..<SNR>155_AddWindowLabels[22]..<SNR>155_OpenPopup,
vim(call):e5555: api call: wrong type for argument 1 when calling nvim_buf_set_lines, expecting buffer

**Comment by dstein64** [comment]
Hi @ghrejoe. Do you have a minimal set of steps I can use to reproduce the issue? What version of Neovim are you using?

**Comment by ghrejoe** [comment]
> Hi @ghrejoe. Do you have a minimal set of steps I can use to reproduce the issue? What version of Neovim are you using?

Sorry for being busy and not responding in a timely manner. My Neovim version is v0.9.4.
I opened more than one tab, then entered vim-win through<leader>w, pressed q(or c) to close the tab, and when I tried to enter vim-win using<leader>w, I reported an error.
Of course, I am not sure if the problem is caused by other plugins. 

In addition, I actually used an old version of Vim-Win before, and when I encountered this problem, I didn't handle it until I found the new version. After reinstalling it, I found that the problem still exists. So I used the old version again and made a few changes to the code, and there were no errors.

...
 elseif has_key(g:win_ext_command_map, l:char)
        if has('nvim') && (l:char ==# 'c' || l:char ==# 'C' || l:char ==# 'q' || l:char ==# 'Q')
          call s:RemoveWindowLabels(l:label_winids)
        endif
        execute l:ext_command
...

**Comment by dstein64** [comment]
Thanks for the reproduction steps.

It sounds like your `g:win_ext_command_map` is configured (at least partially) in a manner similar to what's shown in the documentation:

https://github.com/dstein64/vim-win/blob/0557960c3305b902b5972bbadd2951c71b1f8f96/doc/win.txt#L95-L112

When the last window for a tab is closed, its remaining floating windows are also closed. `vim-win` was encountering an error when trying to close the floating windows (showing `vim-win` window number) that no longer existed. I put a fix in b50013e4682ec91d7f39478911dc9ba2c49afbdd. Does that solve the issue for you?

**Comment by ghrejoe** [comment]
> Thanks for the reproduction steps.
> 
> It sounds like your `g:win_ext_command_map` is configured (at least partially) in a manner similar to what's shown in the documentation:
> 
> https://github.com/dstein64/vim-win/blob/0557960c3305b902b5972bbadd2951c71b1f8f96/doc/win.txt#L95-L112
> 
> When the last window for a tab is closed, its remaining floating windows are also closed. `vim-win` was encountering an error when trying to close the floating windows (showing `vim-win` window number) that no longer existed. I put a fix in [b50013e](https://github.com/dstein64/vim-win/commit/b50013e4682ec91d7f39478911dc9ba2c49afbdd). Does that solve the issue for you?

---

Yes, I have reconfigured g: win_ext_command_map, and modify some of the code to support the nerdtree plugin in deciding where to create the window before opening the file. But I don't know much about Vimscript, so when there were problems before, I thought it was because I modified the code.

I just tried your modifications and tested them several times, and found no errors. Great, thank you!
