### ISSUE TITLE
Window jump supports English letters

### ISSUE THREAD

**Issue by Archdsenna** [dstein64/vim-win#3]
Hi, I am very happy to use this plug-in, which speeds up my window switching. However, I found that I can only use the number keys when switching windows. I checked the help document and found that it does not currently support setting the window numbering style. Considering the cost of key switching, on my keyboard, the number keys are at the top of the keyboard. When I want to press the number keys to jump to the window, I have to move my fingers away from the keyboard core area, press the number keys at the top and then return to the main key position, which interrupts the finger key layout. If the window panel can be represented by English letters, it will be much faster to switch to the window of the corresponding letter without moving the fingers away from the keyboard core area. So whether it can support the function of customizing the window numbering style, I think this is very useful for switching windows at a very low cost.
![image](https://github.com/user-attachments/assets/7e88b1d3-49a8-4aff-bfec-6ad5e559a3d7)

Thanks again!

**Comment by Archdsenna** [comment]
Sorry, the question I asked doesn't seem to make sense, because English letters may be mapped to custom action commands, for example in the g:win_ext_command_map variable, so the current way is very good, I will close this issue. Thanks again for this useful plugin！

**Comment by dstein64** [comment]
Hi @Archdsenna, thanks for proposing the idea. In addition to custom commands, the plugin supports 1) movement keys (`h`, `j`, `k`, `l`) for navigating windows, 2) `s` for swapping buffers, and 3) `w` for window navigation. Those would also conflict with using letters for windows.

But I think there is still a way to add the functionality you proposed. For example, a key like `g` could be used to enter letter mode. When pressed, the numbers would be changed to letters, and letters could be used for navigation. The existing letter functionality would not be available. There could be a way to enter this mode by default (so `g` wouldn't need to be pressed, saving a keystroke).

**Comment by Archdsenna** [comment]
> Hi @Archdsenna, thanks for proposing the idea. In addition to custom commands, the plugin supports 1) movement keys (`h`, `j`, `k`, `l`) for navigating windows, 2) `s` for swapping buffers, and 3) `w` for window navigation. Those would also conflict with using letters for windows.您好@Archdsenna ，感谢您提出这个想法。除了自定义命令之外，该插件还支持 1) 用于导航窗口的移动键（ `h` 、 `j` 、 `k` 、 `l` ），2) `s`用于交换缓冲区，以及 3) `w`用于窗口导航。这些也会与在窗口中使用字母发生冲突。
> 
> But I think there is still a way to add the functionality you proposed. For example, a key like `g` could be used to enter letter mode. When pressed, the numbers would be changed to letters, and letters could be used for navigation. The existing letter functionality would not be available. There could be a way to enter this mode by default (so `g` wouldn't need to be pressed, saving a keystroke).但我认为仍然有一种方法可以添加您提出的功能。例如，像`g`这样的键可用于进入字母模式。当按下时，数字会变成字母，字母可以用于导航。现有的信件功能将不可用。可能有一种方法可以默认进入此模式（因此不需要按下`g` ，从而节省了击键次数）。


Great idea, if I press a key, such as g, I can convert letters to digital display, so that when there are multiple windows, I don't need to press h/j/k/l to reach the target window. Of course, this is just to quickly switch to the target window among multiple windows. The rest of the time, we can still use letter commands normally, which is more reasonable than the English letter navigation I thought before. Will this feature be supported in the future?

**Comment by Archdsenna** [comment]
> Hi @Archdsenna, thanks for proposing the idea. In addition to custom commands, the plugin supports 1) movement keys (`h`, `j`, `k`, `l`) for navigating windows, 2) `s` for swapping buffers, and 3) `w` for window navigation. Those would also conflict with using letters for windows.
> 
> But I think there is still a way to add the functionality you proposed. For example, a key like `g` could be used to enter letter mode. When pressed, the numbers would be changed to letters, and letters could be used for navigation. The existing letter functionality would not be available. There could be a way to enter this mode by default (so `g` wouldn't need to be pressed, saving a keystroke).

Great idea, if I press a key, such as g, I can convert letters to digital display, so that when there are multiple windows, I don't need to press h/j/k/l to reach the target window. Of course, this is just to quickly switch to the target window among multiple windows. The rest of the time, we can still use letter commands normally, which is more reasonable than the English letter navigation I thought before. Will this feature be supported in the future?

**Comment by dstein64** [comment]
> "Will this feature be supported in the future?"

I'm planning to add the feature described [above](https://github.com/dstein64/vim-win/issues/3#issuecomment-2302065249). I'll reopen this issue.

**Comment by dstein64** [comment]
I've added a letter mode that can be entered with `g`. In letter mode, the window labels show letters that are used for navigation instead of window numbers.

> "There could be a way to enter this mode by default (so g wouldn't need to be pressed, saving a keystroke)."

I didn't add a way to make this the default mode; under the current implementation, using `g` is required for letter mode. I'll possibly revisit this in the future.
